spring.application.name=activity-service
server.port=8004

# mongodb database config
spring.mongodb.uri=mongodb://localhost:27017/fitnessactivity
spring.mongodb.database=fitnessactivity

#eureak configuration
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

#rabbitmq configuration
rabbitmq.exchange.name=fitness.exchange
rabbitmq.queue.name=activity.queue
rabbitmq.routing.key=activity.tracking
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest