spring.application.name=USER-SERVICE
server.port=8086
spring.datasource.url=jdbc:postgresql://localhost:5432/fitness_user_db
spring.datasource.username=postgres
spring.datasource.password=00000
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/